name: PR Build Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsfml-dev libomp-dev

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: vcpkg install sfml:x64-windows

    - name: Configure CMake (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build Project
      run: cmake --build build --config Release
